In [1]:
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np
from math import pi

In [2]:
from qiskit import QuantumCircuit, ClassicalRegister, QuantumRegister, execute
from qiskit.tools.visualization import circuit_drawer
from qiskit.quantum_info import state_fidelity
from qiskit import BasicAer

backend = BasicAer.get_backend('unitary_simulator')

In [3]:
# Single qubit gates
#The single-qubit gates available are: - u gates - Identity gate - Pauli gates - Clifford gates - 𝐶3 gates - Standard rotation gates

q = QuantumRegister(1)

In [4]:
# u gate
qc = QuantumCircuit(q)
qc.u3(pi/2,pi/2,pi/2,q)
qc.draw()

<ipython-input-4-f6baa6bc5eee>:3: DeprecationWarning: The QuantumCircuit.u3 method is deprecated as of 0.16.0. It will be removed no earlier than 3 months after the release date. You should use QuantumCircuit.u instead, which acts identically. Alternatively, you can decompose u3 in terms of QuantumCircuit.p and QuantumCircuit.sx: u3(ϴ,φ,λ) = p(φ+π) sx p(ϴ+π) sx p(λ) (2 pulses on hardware).
  qc.u3(pi/2,pi/2,pi/2,q)


┌─────────────────┐
q0_0: ┤ U3(π/2,π/2,π/2) ├
      └─────────────────┘

In [6]:
# This is a useful gate because it allows us to create superpositions
job = execute(qc, backend)
job.result().get_unitary(qc,decimals=3)

array([[ 7.07106781e-01+0.00000000e+00j, -4.32978028e-17-7.07106781e-01j],
       [ 4.32978028e-17+7.07106781e-01j, -7.07106781e-01+8.65956056e-17j]])

In [8]:
qc = QuantumCircuit(q)
qc.u2(pi/2,pi/2,q)
qc.draw()

┌─────────────┐
q0_0: ┤ U2(π/2,π/2) ├
      └─────────────┘

In [9]:
# This is a useful gate because it allows us to apply quantum phase
job = execute(qc, backend)
job.result().get_unitary(qc,decimals=3)

array([[ 7.07106781e-01+0.00000000e+00j, -4.32978028e-17-7.07106781e-01j],
       [ 4.32978028e-17+7.07106781e-01j, -7.07106781e-01+8.65956056e-17j]])

In [11]:
# Identitiy Gate (Id = u0(1))
qc = QuantumCircuit(q)
qc.id(q)
qc.draw()

┌───┐
q0_0: ┤ I ├
      └───┘

In [12]:
job = execute(qc, backend)
job.result().get_unitary(qc,decimals=3)

array([[1.+0.j, 0.+0.j],
       [0.+0.j, 1.+0.j]])

In [13]:
# Pauli Gate: x-bit flip gate x(0 1; 0 1) = u3(pi,0,pi)
qc = QuantumCircuit(q)
qc.x(q)
qc.draw()

┌───┐
q0_0: ┤ X ├
      └───┘

In [14]:
job = execute(qc, backend)
job.result().get_unitary(qc,decimals=3)

array([[0.+0.0000000e+00j, 1.-1.2246468e-16j],
       [1.+0.0000000e+00j, 0.+0.0000000e+00j]])

In [15]:
# Pauli Gate: y-bit flip gate x(0 -i; 0 i) = u3(pi,pi/2,pi/2)
qc = QuantumCircuit(q)
qc.y(q)
qc.draw()

┌───┐
q0_0: ┤ Y ├
      └───┘

In [16]:
job = execute(qc, backend)
job.result().get_unitary(qc,decimals=3)

array([[ 0.000000e+00+0.j, -6.123234e-17-1.j],
       [ 6.123234e-17+1.j,  0.000000e+00+0.j]])

In [17]:
# Pauli Gate: z-bit flip gate x(0 1; 0 -1) = u1(pi)
qc = QuantumCircuit(q)
qc.y(q)
qc.draw()

┌───┐
q0_0: ┤ Y ├
      └───┘

In [18]:
job = execute(qc, backend)
job.result().get_unitary(qc,decimals=3)

array([[ 0.000000e+00+0.j, -6.123234e-17-1.j],
       [ 6.123234e-17+1.j,  0.000000e+00+0.j]])

In [19]:
# Clifford Gate
#hadamard gate H = 1/root(2)(1 1; 1 -1) = u2(0, pi)

qc = QuantumCircuit(q)
qc.h(q)
qc.draw()

┌───┐
q0_0: ┤ H ├
      └───┘

In [20]:
job = execute(qc, backend)
job.result().get_unitary(qc,decimals=3)

array([[ 0.70710678+0.00000000e+00j,  0.70710678-8.65956056e-17j],
       [ 0.70710678+0.00000000e+00j, -0.70710678+8.65956056e-17j]])